# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ion < Formula
  desc "Ion is a all-in-one application to sum up a lot of useful tools in a single command.
The swiss knife for every SysAdmin/DevOps!
"
  homepage "https://github.com/mas2020-golang/ion"
  version "0.3.0-dev.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/ion/releases/download/v0.3.0-dev.3/ion_0.3.0-dev.3_Darwin-x86_64.tar.gz"
      sha256 "92e9eb077f8a931e39cec36945225ae853386581549f4a6441df89a3b247e47e"

      def install
        bin.install "ion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mas2020-golang/ion/releases/download/v0.3.0-dev.3/ion_0.3.0-dev.3_Darwin-arm64.tar.gz"
      sha256 "b89261949793c505f835e7cafed53f4a56627bf19ee8548235ab99f819db5a69"

      def install
        bin.install "ion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/ion/releases/download/v0.3.0-dev.3/ion_0.3.0-dev.3_Linux-x86_64.tar.gz"
      sha256 "24979e9bcc68308d75ee173395fedbd083555b31d8e3222db4c2bed58af9fda8"

      def install
        bin.install "ion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mas2020-golang/ion/releases/download/v0.3.0-dev.3/ion_0.3.0-dev.3_Linux-arm64.tar.gz"
      sha256 "ac1ea7b6360f49dd94a10e5b79102f6e1927ab4e70d5daffaba2115204fe30ce"

      def install
        bin.install "ion"
      end
    end
  end
end
